language: clojure

script: "./.travis/test.sh"

sudo: required

addons:
  chrome: stable

cache:
  directories:
  - $HOME/.m2

jdk:
- oraclejdk8

addons:
  ssh_known_hosts:
  - ventas.kazer.es

after_success:
- CLOVERAGE_VERSION=1.0.10 lein cloverage --codecov
- bash <(curl -s https://codecov.io/bash)