version: '2'
services:

  datomic:
    image: datomic
    ports:
      - 4334
    volumes:
      - datomic:/opt/datomic-pro-0.9.5561/data

  ventas:
    image: ventas
    ports:
        - ${LOCAL_PORT}:${SERVER__PORT}
    depends_on:
      - datomic
    env_file:
        - .env
    volumes:
        - ./storage:/storage

volumes:
  datomic:
    driver: local