version: '2'
services:

  datomic:
    image: datomic
    ports:
      - 4334:4334
      - 4335:4335
      - 4336:4336
    volumes:
      - datomic:/opt/datomic-pro-0.9.5561/data

  ventas:
    image: ventas
    ports:
      - ${LOCAL_PORT}:${SERVER__PORT}
    depends_on:
      - datomic
      - elasticsearch
      - kafka
      - chrome
    env_file:
        - .env
    volumes:
        - ./storage:/storage

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  chrome:
    image: robcherry/docker-chromedriver:latest
    ports:
      - 4444:4444
    environment:
      - "CHROMEDRIVER_WHITELISTED_IPS=''"
    privileged: true

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:1.1.0
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  elasticsearch:
    driver: local
  datomic:
    driver: local
