version: '2'
services:

  datomic:
    image: datomic
    ports:
      - 4334

  ventas:
    image: ventas
    ports:
        - ${LOCAL_PORT}:${SERVER__PORT}
    depends_on:
      - datomic
    env_file:
        - .env
